- newscript.go
If we are trying to copy a file to a place we need to remove the one that's
there. We remove it as it might be a symlink and opening and writing to it
will lead to some other file being written, which is bad.
We are once again copying CONFIG to linux-stable/.config; I forgot
that the make process in linux can change .config a lot.
> newscript: remove files we copy to; copy CONFIG to linux-stable/.config

- travis.sh
- usb/usb.go
It's painful to redo the full pull each time.
Default fetch to false. If you want a clean
build, as in travis, use -fetch=true.
> default fetch to false

- uinit/uinit.go
- usb/tczlist.go
The uinit will take care of setting up all packages and doing
other housekeeping that's not really the job of xinit.
> Add a uinit for NiChrome

- travis.sh
- usb/usb.go
ChromeOS rules for the USB stick are tightly fixed: when you know the
kern partition, you know the root partition.
Hence, we'll just ask for the kern device, via a switch, and also
whether we're doing A or B, via a switch, and then figure out which
partitions to use. Device /dev/null is a special case; we'll just
use /dev/null for kern and root.
We also remove the interactive selection of the device, it makes
scripting harder and is in the end not that convenient -- if you need
to type the device name, do so on the command line via the switch.
> dev: change how we pick our device

- usb/usb.go
I toasted my hard drive last night (systemd grrrrr systemd) but
this allows me to test things better.
add the bc and libssl-dev packages
Set ARCH when we build linux, so that an inherited ARCH
does not cause trouble.
> usb: fix 3 build problems

- usb/usb.go
This error was missed by travis because travis always
starts with a clean directory.
> build: remove linux-firmware directory when we fetch

- cmds/uinit/uinit.go
- usb/usb.go
This is now tested and we can run chrome as user 1000.
two things remain:
You need to have an etc/passwd in the Nichrome directory.
fusermount stupidly requires it. Until we have a less
stupid fusermount in u-root we're stuck with this
requirement.
I have this:
root:x:0:0:root:/:/bin/bash
user:x:1000:1000:user:/:/bin/bash
You need to, on boot, chmod 0666 /dev/fuse
Right now, we don't automagically start user code. You have to do this manually:
uinit -usernamespace
once you have the user shell,
wingo
and if you want
chrome
This is all very new, it was required by our need to run Chrome as non-root.
> Support multiple user ids

- usb/usb.go
usb command used to throw error when u-root's gpt command not install on
the device. This fix now will install the gpt command before building
the kernel image.
Signed-off-by: Thien M. Hoang <thienhoang@google.com>
> Fixes u-root/NiChrome#58: usb command will install u-root's gpt cmd before building kernel image.

- cmds/uinit/uinit.go
> Return directly in instances where we don't read the error value

- travis.sh
Some systems might not have all the libraries required, install them if
needed.
Signed-off-by: Gan Shun Lim <ganshun@gmail.com>
> Add apt=true for travis

- usb/usb.go
Determine which packages are missing, and then install them.
I think this makes the utility more user friendly, because they don't need
to know which command line flags to use for the first time run.
Users can still set the flag to false at runtime.
TEST=automated testing framework
> Always check for missing packages when invoking USB

- cmds/uinit/uinit.go
Replaced string slice of commands to run at startup with startupCmds, declared at top for easy additions.
Added "upspin" command to support [u-root/bdf1401](https://github.com/u-root/u-root/pull/764/commits/bdf1401ce082c6b0cb59ebab04a7dce0f9a7f693)
> cmds/uinit/uinit.go: Moved declaration of startup commands to top of file

- cmds/uinit/uinit.go
Mostly for Upspin integration. As long as `userenv` is not an empty string, Upspin will be happy.
> Set $USER environment variable for non-root users on boot

- usb/usb.go
For now, these are extremely useful to have around until we write
them in Go. Also, build them statically, so we don't have to deal
with stupid shared library problems.
I've tested this and it's really nice to have them there.
> vboot: compile vboot tools statically and add them to the image

- Gopkg.lock
- cmds/install/install.go
- cmds/uinit/uinit.go
Just doing a dumb raw dd of partitions is too dangerous.
This way we can figure out if the cpio is valid and not
copy the whole partition if the cpio is smaller (and it
is by a lot).
> install: use a cpio passthrough function for root

- usb/usb.go
This reverts PR #102 due to C build issues on some Linux systems.
> Revert "vboot: compile vboot tools statically and add them to the image"

- verified_boot.md
After failing to install NiChrome on Falco (older) and Eve (newer) devices, I figured we should start compiling a list of publicly-released devices that these instructions work on.
> vboot-docs: add list of working devices

- QRUN
- cmds/uinit/uinit.go
This introduces a new KERNEL command line switch, nichromeroot
if nichromeroot is in the command line, the uinit command will
look for the parameter, e.g.
nichromeroot=/dev/sda
will cause uinit to grab the cpio from /dev/sda
(not a typo! by using /dev/sda, not /dev/sda2, we don't
have to mess with partitions in the qemu hard drive)
This makes a certain amount of testing possible.
X won't work right now, but we can get to that later.
It will finally be possible to test NiChrome in qemu,
unlink ChromeOS.
QRUN is a sample QEMU usage.
I replicate it here for history.
First, we can do this:
go run usb/*.go -dev=/tmp/t
usb will create two files, /tmp/t2 and /tmp/t3.
t3 is the cpio image.
Then we can run qemu
qemu-system-x86_64 \
-m 2048M \
-kernel linux-stable/arch/x86/boot/bzImage \
-s \ …
> QEMU: allow us to run from QEMU for testing

- cmds/uinit/uinit.go
Not sure why we don't use cmd.Args(), there must be a reason.
> uinit: fix internal commands to use pflag format

- usb/usb.go
This builds and boots in ^U. Not tested as a recovery stick.
> Move to go modules

- verified_boot.md
We removed the vboot_reference tools in #111 due to build issues, but we didn't update the vboot documentation to reflect that.
> vboot: remove references to NiChrome's cgpt script
