u-root/NiChrome

.travis.yml
travis.sh

For now it's limited to making sure the kernel build still works.

Add travis testing for NiChrome

---

newscript.go

Sorry about the previous confusion, please see here for more changes (this has not been tested yet locally, but I'll push every change I make) .

new branch, new PR

---

newscript.go
travis.sh

The travis is now a run of newscript.go
So no more commits will happen that break the build.

fix building and testing

---

newscript.go

The script was not quitting on errors, and it was lacking
a package.

newscript: correctly quit on errors, add uuid-dev

---

newscript.go
travis.sh

To add a new command, add a new file and put the command in the table.

newscript: make it so anyone can run travis; clean up commands

---

newscript.go

newscript: move build buildVbutil into the table and don't ignore error

---

usb/tczlist.go

note that this requires PR 356 to be approved from the u-root repo
to work.

wireless: add a wireless tcz

---

usb/urootlist.go

wireless: add the wifi tool

---

usb/usb.go

fixbuild: building on linode showed a bug in the building

---

.gitignore

ignore more files we don't care about

---

install/install.go
uinit/uinit.go
usb/urootlist.go
usb/usb.go

this install command is what you run to install NiChrome on a chromebook.
usage:
install <target-name>
For now it will always install on the B image
I've tested this on a chromebook and it works.
You do this:
boot the usb
install
remove usb and boot into chromeos
cgpt add -P 2 -T 1 -i 4 /dev/mmcblk1 # or whatever you device is)
reboot
and it goes to NiChrome, once. Next time you boot it's back to chromeos.

install command

---

usb/usb.go

we just use a build tag now instead.

usb: remove goversion test

---

usb/usb.go

Signed-off-by: Thien Hoang <thienhoang@google.com>

Fixes #66: Add Umask(0) to usb setup function

---

usb/usb.go

Signed-off-by: Thien Hoang <thienhoang@google.com>

Fix #67: usb will use rsync to pull fusermount binary from /bin into usr/bin

---

usb/usb.go

This should speed up builds that are cpu constrained.
TEST=automated framework

Make worker threads dynamic at runtime

---

usb/usb.go

Return directly in instances where we don't read the error value

---

usb/usb.go

Our working directory is linux-stable for the kernel.
TEST=automated testingframework, ./usb/usb --fetch

Remove unused cleanup variable

---

cmds/uinit/uinit.go

Test: compiled and ran on test chromebook
Signed-off-by: Thien Hoang <thienhoang@google.com>

uinit will create /etc/hosts file

---

cmds/uinit/uinit.go

A terrible, but cautious and useful, hack.

cmds/uinit: fix problem of cpio setting perms on / incorrectly

---

usb/usb.go

You can say, e.g.
go run usb/*.go -extra github.com/yudai/gotty
These will be added to the dynamicCmdList
If fetch is enabled, they will hence be included in things to get.
In any event, they are included in things to have on root file system.

usb: add -extra flag for extra packages/commands

---

usb/usb.go

Signed-off-by: jbetancourt <jmbetancourt@google.com>

add html files to archive when building usb

---

usb/usb.go

Signed-off-by: jbetancourt <jmbetancourt@google.com>

edit path for html files

---

usb/usb.go

Signed-off-by: jbetancourt <jmbetancourt@google.com>

put html files in etc folder

---

usb/usb.go

usb: add a note about recovery kernels

---

cmds/uinit/uinit.go

/home/user is not created on boot

Moves user environment from / to /home/user

---

usb/usb.go

This is making our chromebook like much easier.

usb: Use the recovery keys since this is a usb stick

---

verified_boot.md

Adds documentation regarding boot in Verified mode.

---

cmds/install/install.go

Signed-off-by: jbetancourt <jmbetancourt@google.com>

factor out function to be called from cpio pkg

---

sound_progress.md
usr/sound.sh

document progress made on sound implementation

---

cmds/uinit/uinit.go

We did this for root commands a few months ago, I figured it'd be good to do for user commands too.

uinit: extract user startup commands

---

cmds/uinit/uinit.go

uinit: start time_sos on startup

---

cmds/uinit/uinit.go
usb/usb.go

This resolves the final set of changes to deal with u-root changes.

Final fix for u-root changes

---

RELEASES

This got done late but better late than never.

Release of v1

---

cmds/uinit/uinit.go

They changed at some point and we did not keep up

Fix naming of time and upspin services

---

cmds/install/install.go
cmds/uinit/uinit.go
usb/tczlist.go
usb/urootlist.go
usb/usb.go

add copyrights and build constraints

---

.gitignore

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

Ignore .bb/ directories
